### ISSUE TITLE
DISABLE_AUTHENTICATION no longer works

### ISSUE THREAD

**Issue by lwis** [restic/rest-server#119]
Docker version: 3598be715f32

How did you run rest-server exactly?
------------------------------------
Docker

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem

Expected behavior
-----------------
Flag referenced in README to be used to disable authentication.

Actual behavior
---------------
```
web_1  | Data directory: /data
web_1  | Authentication enabled
web_1  | error: cannot load .htpasswd (use --no-auth to disable): stat /data/.htpasswd: no such file or directory
```

Steps to reproduce the behavior
-------------------------------
```
version: '3'
services:
  web:
    image: restic/rest-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DISABLE_AUTHENTICATION: "true"
    volumes:
      - "/dir:/data"
```

Do you have any idea what may have caused this?
-----------------------------------------------
Regression

Do you have an idea how to solve the issue?
-------------------------------------------
Not at an immediate glance.

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
I love the project(s)!
