### ISSUE TITLE
Broken deduplication with REST --private-repos

### ISSUE THREAD

**Issue by Gaibhne** [restic/rest-server#172]
Output of `rest-server --version` 
---------------------------------
[joerg@braemar ~]$ docker images restic/rest-server:latest -q
3598be715f32

I do however not believe that the above command shows anything useful/applicable to my case; I built restic-rest from a fresh repository checkout.

How did you run rest-server exactly?
------------------------------------
Via `docker-compose`:

```yaml
---

version: '3'

services:
  restserver:
    build: rest-server #contains this repository with no changes as of the day of posting this
    volumes:
      - /mnt/usb-01/restic:/data
    environment:
      OPTIONS: "--private-repos --path /data"
    ports:
      - "3000:8000"
```

The reason I build my own is because I run on Raspberry Pi 4 and there are no arm images on Docker hub.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Regular USB HDD with `btrfs`.

Expected behavior
-----------------
I would expect deduplication to happen when two users back up the same data to the repository.

Actual behavior
---------------
No deduplication happens. After the second user backs up their data, the root folder is twice the size.

Steps to reproduce the behavior
-------------------------------
I followed the instructions from the repo to set up Restic REST with multi user support with no special steps or deviations.

Do you have any idea what may have caused this?
-----------------------------------------------
No. It looks like instead of having one repo with multiple users, I just have multiple repos as if I was running individual servers.

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
Cool idea, but I am still in the initial steps of figuring out how to set it up before ever actually using it, so I have yet to experience anything exciting :(
