### ISSUE TITLE
Cannot change the listen port on docker container

### ISSUE THREAD

**Issue by alphadijkstra** [restic/rest-server#286]
Output of `rest-server --version` 
---------------------------------
docker 0384c3e2599f

How did you run rest-server exactly?
------------------------------------

```
version: "3.2"
services:
  resticrestserver:
    image: restic/rest-server:latest
    container_name: resticrestserver
    volumes:
      - /mnt/cache/docker/config/restic_restserver/data:/data
    ports:
    - "6333:6333" #Restic REST listen port server
    environment:
      DISABLE_AUTHENTICATION: 1
      OPTIONS: --listen ":6333"
    restart: always
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N.A.

Expected behavior
-----------------

Rest server should work on listen port 6333

Actual behavior
---------------
```
resticrestserver   | Data directory: /data
resticrestserver   | Authentication disabled
resticrestserver   | Private repositories disabled
resticrestserver   | error: unable to listen: listen on ':6333' failed: listen tcp: address tcp/6333': unknown port
```

Steps to reproduce the behavior
-------------------------------

Using the above docker-compose.yml.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------
I am really intrigued by rest server, but cannot get it to work in this way. I need to use a different listen port. Other than 8000.
