### ISSUE TITLE
unknown flag: --tls

### ISSUE THREAD

**Issue by ilium007** [restic/rest-server#304]
Output of `rest-server --version` 
---------------------------------
root@pbs:~# docker images restic/rest-server:latest -q
cd6786ee5f42

How did you run rest-server exactly?
------------------------------------
docker compose

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local disk

Expected behavior
-----------------
Flag --tls not recognised

I noticed this issue when I went looking as to why my SSL certs weren't being picked up.

Actual behavior
---------------

docker-compose.yml

```
services:
  rest-server:
    image: restic/rest-server:latest
    container_name: rest-server
    volumes:
      - /mnt/storage0/rest-server:/data
    ports:
      - 8000:8000
    environment:
      - OPTIONS="--private-repos --tls"
    restart: unless-stopped
```

```
root@pbs:~# docker compose up
[+] Running 2/1
 ✔ Network root_default   Created                                                                                                                                                                                                      0.1s
 ✔ Container rest-server  Created                                                                                                                                                                                                      0.1s
Attaching to rest-server
rest-server  | 2024/09/18 11:59:56 error: unknown flag: --tls"
rest-server exited with code 1
rest-server  | 2024/09/18 11:59:56 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:56 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:56 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:58 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:56 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:57 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:58 error: unknown flag: --tls"
rest-server  | 2024/09/18 11:59:59 error: unknown flag: --tls"
```

Steps to reproduce the behavior
-------------------------------

Run docker compose file above

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did rest-server help you today? Did it make you happy in any way?
-----------------------------------------------------------------

rest-server is awesome!

**Comment by ilium007** [comment]
The docker compose.

--debug is also ignored:

```
root@pbs:~# cat docker-compose.yml
services:
  rest-server:
    image: restic/rest-server:latest
    container_name: rest-server
    volumes:
      - /mnt/storage0/rest-server:/data
    ports:
      - 8000:8000
    environment:
      - OPTIONS:"--debug --private-repos --tls"
    restart: unless-stopped
```


```
root@pbs:~# docker compose up
[+] Running 1/0
 ✔ Container rest-server  Created                                                                                                                                                                                                      0.0s
Attaching to rest-server
rest-server  | Data directory: /data
rest-server  | Authentication enabled
rest-server  | Loaded htpasswd file /data/.htpasswd
rest-server  | Private repositories disabled
rest-server  | start server on [::]:8000
```
