### ISSUE TITLE
Prometheus env question - docker (compose)

### ISSUE THREAD

**Issue by 1mfaasj** [restic/rest-server#310]
Hello, I have a quick question, which may not even be a bug but I want to make sure.
When I set the OPTIONS prometheus environment, restic indicates that it is not recognized.

Do I have to build the restic server myself for this? but how do I get Prometheus support in it?
So in other words, there isn't prometheus in the docker image by default when I deploy it like this?

```
services:
  restic:
    container_name: restic
    image: restic/rest-server
    ports:
      - 8000:8000
    environment:
      - DISABLE_AUTHENTICATION=true
      - OPTIONS=--prometheus
    volumes:
      - /mnt/exdisk/restic:/data
```

Also other variants of OPTIONS do not work, so for instance when I:
`      - OPTIONS="--prometheus"`
 or:
`       - "OPTIONS=--prometheus"`
